### ISSUE TITLE
npm run generate throws error. 

### ISSUE THREAD

**Issue by ErikCH** [joelvarty/agility-nuxt-app#1]
When I run

```npm run generate```

I get this error. 

```Entrypoint app = server.js
on client                                                                                                    19:07:06

 ERROR  Could not resolve routes                                                                             19:07:06


 FATAL  document is not defined                                                                              19:07:06

  at AgilityClient.checkPreviewModeAndLanguageCode (agility/agility-client.js:53:36)
  at AgilityClient.createClient (agility/agility-client.js:18:8)
  at new AgilityClient (agility/agility-client.js:9:22)
  at routes (nuxt.config.js:111:26)
  at Object.promisifyRoute (node_modules/@nuxt/utils/dist/utils.js:1740:17)
  at Generator.initRoutes (node_modules/@nuxt/generator/dist/generator.js:84:38)
  at Generator.generate (node_modules/@nuxt/generator/dist/generator.js:44:31)
  at async Object.run (node_modules/@nuxt/cli/dist/cli-generate.js:107:24)
  at async NuxtCommand.run (node_modules/@nuxt/cli/dist/cli-index.js:2759:7)```

I'm running node v12.16.1

**Comment by joelvarty** [comment]
Hi Erik - nice find.  I haven't looked at this code for a while, and I don't know if static site generation was ever working properly.  I will flush out this example and also convert it over to use the newer Agility Sync SDK for increased build speed.

**Comment by joelvarty** [comment]
I haven't been able to repro this... how would you feel joining our [Slack Dev Community](https://join.slack.com/t/agilitycommunity/shared_invite/enQtNzI2NDc3MzU4Njc2LWI2OTNjZTI3ZGY1NWRiNTYzNmEyNmI0MGZlZTRkYzI3NmRjNzkxYmI5YTZjNTg2ZTk4NGUzNjg5NzY3OWViZGI)?  That way we can collaborate more easily.
